{% set version = "1.5.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shades
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shades_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shades/shades_{{ version }}.tar.gz
  sha256: 848398c2e1c10e9c95582841867bb3d1143ff8495047fab03313fe239feed2ac

build:
  number: 0
  noarch: generic
  script: $R CMD INSTALL --build .     # [unix]
  script: "%R%" CMD INSTALL --build .  # [win]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('shades')"           # [not win]
    - "\"%R%\" -e \"library('shades')\""  # [win]

about:
  home: https://github.com/jonclayden/shades
  license: BSD_3_clause
  summary: Functions for easily manipulating colours, creating colour scales and calculating colour distances.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENCE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: shades
# Version: 1.4.0
# Date: 2019-08-02
# Title: Simple Colour Manipulation
# Author: Jon Clayden
# Maintainer: Jon Clayden <code@clayden.org>
# Description: Functions for easily manipulating colours, creating colour scales and calculating colour distances.
# Suggests: testthat, covr, ggplot2
# Enhances: colorspace
# Encoding: UTF-8
# License: BSD_3_clause + file LICENCE
# URL: https://github.com/jonclayden/shades
# BugReports: https://github.com/jonclayden/shades/issues
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-08-02 14:53:11 UTC; jon
# Repository: CRAN
# Date/Publication: 2019-08-02 16:00:02 UTC
