{% set version = "1.5.0" %}

package:
  name: r-shades
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shades_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shades/shades_{{ version }}.tar.gz
  sha256: 848398c2e1c10e9c95582841867bb3d1143ff8495047fab03313fe239feed2ac

build:
  number: 0
  noarch: generic
  script: $R CMD INSTALL --build .         # [unix]
  script: "\"%R%\" CMD INSTALL --build ."  # [win]
  script_env:
    DISABLE_AUTOBREW: "1"

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('shades')"           # [not win]
    - "\"%R%\" -e \"library('shades')\""  # [win]

about:
  home: https://github.com/jonclayden/shades
  license: BSD-3-Clause
  summary: Functions for easily manipulating colours, creating colour scales and calculating colour distances.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENCE

extra:
  recipe-maintainers:
    - conda-forge/r
